---
# Per environment values which override defaults in hmpps-prisoner-pay-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prisoner-pay-preprod.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://prisoner-pay-preprod.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-preprod.hmpps.service.justice.gov.uk"
    ACTIVITIES_UI_URL: "https://activities-preprod.prison.service.justice.gov.uk/activities"
    PRISON_API_URL: "https://prison-api-preprod.prison.service.justice.gov.uk"
    DIGITAL_PRISON_SERVICE_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    EXAMPLE_API_URL: 'https://template-kotlin-preprod.hmpps.service.justice.gov.uk'
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-activities-management-dev
